#pragma once
#define PACKET_MIN_TIME 30
#define PACKET_MAX_TIME 90
#define PERIODIC_CALL_RATE 1
#define REFRESH_RATE 33
#define LATENCY_POLL_RATE 500
#define X_ORIGIN 0
#define Y_ORIGIN 0
#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 500
#define PADDLE_SPEED 10
#define PADDLE_HEIGHT 100
#define PADDLE_WIDTH 30
#define BALL_HEIGHT 90
#define BALL_WIDTH 90
#define VERT_WALL_WIDTH 20
#define VERT_WALL_HEIGHT 500
#define HORIZ_WALL_WIDTH 110
#define HORIZ_WALL_HEIGHT 20

